name: simple-music-uploader

services:
    app:
        build:
            context: .
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        restart: always
        volumes:
            - ./music:/data/music
        ports:
            - "5062:8000"
